/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrowserRouteImport } from './routes/browser'
import { Route as CoachingRouteImport } from './routes/coaching'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MailRouteImport } from './routes/mail'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as TargetRouteImport } from './routes/target'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as ChatCodeRouteImport } from './routes/chat.$code'
import { Route as ClassCodeRouteImport } from './routes/class.$code'
import { Route as CustomStudyDeckIdRouteImport } from './routes/custom-study.$deckId'
import { Route as DiscussCodeRouteImport } from './routes/discuss.$code'
import { Route as NotesNoteIdRouteImport } from './routes/notes_.$noteId'
import { Route as OptionsDeckIdRouteImport } from './routes/options.$deckId'
import { Route as OverviewDeckIdRouteImport } from './routes/overview.$deckId'
import { Route as QuizCodeRouteImport } from './routes/quiz.$code'
import { Route as SessionDeckIdRouteImport } from './routes/session.$deckId'
import { Route as StudyDeckIdRouteImport } from './routes/study.$deckId'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates_.$templateId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserRoute = BrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingRoute = CoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetRoute = TargetRouteImport.update({
  id: '/target',
  path: '/target',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatCodeRoute = ChatCodeRouteImport.update({
  id: '/chat/$code',
  path: '/chat/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassCodeRoute = ClassCodeRouteImport.update({
  id: '/class/$code',
  path: '/class/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomStudyDeckIdRoute = CustomStudyDeckIdRouteImport.update({
  id: '/custom-study/$deckId',
  path: '/custom-study/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussCodeRoute = DiscussCodeRouteImport.update({
  id: '/discuss/$code',
  path: '/discuss/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes_/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsDeckIdRoute = OptionsDeckIdRouteImport.update({
  id: '/options/$deckId',
  path: '/options/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewDeckIdRoute = OverviewDeckIdRouteImport.update({
  id: '/overview/$deckId',
  path: '/overview/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizCodeRoute = QuizCodeRouteImport.update({
  id: '/quiz/$code',
  path: '/quiz/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionDeckIdRoute = SessionDeckIdRouteImport.update({
  id: '/session/$deckId',
  path: '/session/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyDeckIdRoute = StudyDeckIdRouteImport.update({
  id: '/study/$deckId',
  path: '/study/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/templates_/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/admin': typeof AdminRoute
  '/browser': typeof BrowserRoute
  '/coaching': typeof CoachingRoute
  '/connect': typeof ConnectRoute
  '/delete-account': typeof DeleteAccountRoute
  '/desk': typeof DeskRoute
  '/focus': typeof FocusRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRoute
  '/notes': typeof NotesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/target': typeof TargetRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/chat/$code': typeof ChatCodeRoute
  '/class/$code': typeof ClassCodeRoute
  '/custom-study/$deckId': typeof CustomStudyDeckIdRoute
  '/discuss/$code': typeof DiscussCodeRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/options/$deckId': typeof OptionsDeckIdRoute
  '/overview/$deckId': typeof OverviewDeckIdRoute
  '/quiz/$code': typeof QuizCodeRoute
  '/session/$deckId': typeof SessionDeckIdRoute
  '/study/$deckId': typeof StudyDeckIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/admin': typeof AdminRoute
  '/browser': typeof BrowserRoute
  '/coaching': typeof CoachingRoute
  '/connect': typeof ConnectRoute
  '/delete-account': typeof DeleteAccountRoute
  '/desk': typeof DeskRoute
  '/focus': typeof FocusRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRoute
  '/notes': typeof NotesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/target': typeof TargetRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/chat/$code': typeof ChatCodeRoute
  '/class/$code': typeof ClassCodeRoute
  '/custom-study/$deckId': typeof CustomStudyDeckIdRoute
  '/discuss/$code': typeof DiscussCodeRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/options/$deckId': typeof OptionsDeckIdRoute
  '/overview/$deckId': typeof OverviewDeckIdRoute
  '/quiz/$code': typeof QuizCodeRoute
  '/session/$deckId': typeof SessionDeckIdRoute
  '/study/$deckId': typeof StudyDeckIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/admin': typeof AdminRoute
  '/browser': typeof BrowserRoute
  '/coaching': typeof CoachingRoute
  '/connect': typeof ConnectRoute
  '/delete-account': typeof DeleteAccountRoute
  '/desk': typeof DeskRoute
  '/focus': typeof FocusRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRoute
  '/notes': typeof NotesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/target': typeof TargetRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/chat/$code': typeof ChatCodeRoute
  '/class/$code': typeof ClassCodeRoute
  '/custom-study/$deckId': typeof CustomStudyDeckIdRoute
  '/discuss/$code': typeof DiscussCodeRoute
  '/notes_/$noteId': typeof NotesNoteIdRoute
  '/options/$deckId': typeof OptionsDeckIdRoute
  '/overview/$deckId': typeof OverviewDeckIdRoute
  '/quiz/$code': typeof QuizCodeRoute
  '/session/$deckId': typeof SessionDeckIdRoute
  '/study/$deckId': typeof StudyDeckIdRoute
  '/templates_/$templateId': typeof TemplatesTemplateIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/admin'
    | '/browser'
    | '/coaching'
    | '/connect'
    | '/delete-account'
    | '/desk'
    | '/focus'
    | '/friends'
    | '/login'
    | '/mail'
    | '/notes'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/stats'
    | '/subscriptions'
    | '/target'
    | '/templates'
    | '/terms'
    | '/api/rtc'
    | '/chat/$code'
    | '/class/$code'
    | '/custom-study/$deckId'
    | '/discuss/$code'
    | '/notes/$noteId'
    | '/options/$deckId'
    | '/overview/$deckId'
    | '/quiz/$code'
    | '/session/$deckId'
    | '/study/$deckId'
    | '/templates/$templateId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/admin'
    | '/browser'
    | '/coaching'
    | '/connect'
    | '/delete-account'
    | '/desk'
    | '/focus'
    | '/friends'
    | '/login'
    | '/mail'
    | '/notes'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/stats'
    | '/subscriptions'
    | '/target'
    | '/templates'
    | '/terms'
    | '/api/rtc'
    | '/chat/$code'
    | '/class/$code'
    | '/custom-study/$deckId'
    | '/discuss/$code'
    | '/notes/$noteId'
    | '/options/$deckId'
    | '/overview/$deckId'
    | '/quiz/$code'
    | '/session/$deckId'
    | '/study/$deckId'
    | '/templates/$templateId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/admin'
    | '/browser'
    | '/coaching'
    | '/connect'
    | '/delete-account'
    | '/desk'
    | '/focus'
    | '/friends'
    | '/login'
    | '/mail'
    | '/notes'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/stats'
    | '/subscriptions'
    | '/target'
    | '/templates'
    | '/terms'
    | '/api/rtc'
    | '/chat/$code'
    | '/class/$code'
    | '/custom-study/$deckId'
    | '/discuss/$code'
    | '/notes_/$noteId'
    | '/options/$deckId'
    | '/overview/$deckId'
    | '/quiz/$code'
    | '/session/$deckId'
    | '/study/$deckId'
    | '/templates_/$templateId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AdminRoute: typeof AdminRoute
  BrowserRoute: typeof BrowserRoute
  CoachingRoute: typeof CoachingRoute
  ConnectRoute: typeof ConnectRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  DeskRoute: typeof DeskRoute
  FocusRoute: typeof FocusRoute
  FriendsRoute: typeof FriendsRoute
  LoginRoute: typeof LoginRoute
  MailRoute: typeof MailRoute
  NotesRoute: typeof NotesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TargetRoute: typeof TargetRoute
  TemplatesRoute: typeof TemplatesRoute
  TermsRoute: typeof TermsRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ChatCodeRoute: typeof ChatCodeRoute
  ClassCodeRoute: typeof ClassCodeRoute
  CustomStudyDeckIdRoute: typeof CustomStudyDeckIdRoute
  DiscussCodeRoute: typeof DiscussCodeRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  OptionsDeckIdRoute: typeof OptionsDeckIdRoute
  OverviewDeckIdRoute: typeof OverviewDeckIdRoute
  QuizCodeRoute: typeof QuizCodeRoute
  SessionDeckIdRoute: typeof SessionDeckIdRoute
  StudyDeckIdRoute: typeof StudyDeckIdRoute
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser': {
      id: '/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof BrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching': {
      id: '/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof CoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/target': {
      id: '/target'
      path: '/target'
      fullPath: '/target'
      preLoaderRoute: typeof TargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$code': {
      id: '/chat/$code'
      path: '/chat/$code'
      fullPath: '/chat/$code'
      preLoaderRoute: typeof ChatCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$code': {
      id: '/class/$code'
      path: '/class/$code'
      fullPath: '/class/$code'
      preLoaderRoute: typeof ClassCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-study/$deckId': {
      id: '/custom-study/$deckId'
      path: '/custom-study/$deckId'
      fullPath: '/custom-study/$deckId'
      preLoaderRoute: typeof CustomStudyDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discuss/$code': {
      id: '/discuss/$code'
      path: '/discuss/$code'
      fullPath: '/discuss/$code'
      preLoaderRoute: typeof DiscussCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes_/$noteId': {
      id: '/notes_/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options/$deckId': {
      id: '/options/$deckId'
      path: '/options/$deckId'
      fullPath: '/options/$deckId'
      preLoaderRoute: typeof OptionsDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview/$deckId': {
      id: '/overview/$deckId'
      path: '/overview/$deckId'
      fullPath: '/overview/$deckId'
      preLoaderRoute: typeof OverviewDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$code': {
      id: '/quiz/$code'
      path: '/quiz/$code'
      fullPath: '/quiz/$code'
      preLoaderRoute: typeof QuizCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$deckId': {
      id: '/session/$deckId'
      path: '/session/$deckId'
      fullPath: '/session/$deckId'
      preLoaderRoute: typeof SessionDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$deckId': {
      id: '/study/$deckId'
      path: '/study/$deckId'
      fullPath: '/study/$deckId'
      preLoaderRoute: typeof StudyDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates_/$templateId': {
      id: '/templates_/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AdminRoute: AdminRoute,
  BrowserRoute: BrowserRoute,
  CoachingRoute: CoachingRoute,
  ConnectRoute: ConnectRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  DeskRoute: DeskRoute,
  FocusRoute: FocusRoute,
  FriendsRoute: FriendsRoute,
  LoginRoute: LoginRoute,
  MailRoute: MailRoute,
  NotesRoute: NotesRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TargetRoute: TargetRoute,
  TemplatesRoute: TemplatesRoute,
  TermsRoute: TermsRoute,
  ApiRtcRoute: ApiRtcRoute,
  ChatCodeRoute: ChatCodeRoute,
  ClassCodeRoute: ClassCodeRoute,
  CustomStudyDeckIdRoute: CustomStudyDeckIdRoute,
  DiscussCodeRoute: DiscussCodeRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  OptionsDeckIdRoute: OptionsDeckIdRoute,
  OverviewDeckIdRoute: OverviewDeckIdRoute,
  QuizCodeRoute: QuizCodeRoute,
  SessionDeckIdRoute: SessionDeckIdRoute,
  StudyDeckIdRoute: StudyDeckIdRoute,
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
